# Generated by Django 5.1.1 on 2024-09-15 13:43

import task.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', task.fields.EncryptedTextField(max_length=200)),
                ('description', task.fields.EncryptedTextField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
